package cmd

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"awsmux/internal/core"
)

// `awsmux demo` wraps any awsmux command in a sandboxed, fully offline
// environment: a fictional 13-profile fleet served by the hidden fake-aws
// emulator, with its own AWS config and its own state directory. Nothing
// touches real AWS, real credentials, or real awsmux history.

var demoCmd = &cobra.Command{
	Use:   "demo [any awsmux command...]",
	Short: "Try every awsmux feature against a fake 12-account fleet, no AWS needed",
	Long: "Runs the given awsmux command against a fictional fleet (payments, search,\n" +
		"platform, media, data, security, sandbox; prod and stage). Zero AWS setup,\n" +
		"zero credentials, zero network calls, zero risk. State lives in\n" +
		"~/.awsmux/demo; delete that directory to reset the playground.",
	DisableFlagParsing: true,
	RunE:               runDemo,
}

func init() {
	rootCmd.AddCommand(demoCmd)
}

func runDemo(cmd *cobra.Command, args []string) error {
	if len(args) == 0 || args[0] == "--help" || args[0] == "-h" {
		printDemoTour(cmd.OutOrStdout())
		return nil
	}
	if args[0] == "demo" {
		return Exitf(core.ExitConfigError, "already in demo mode; drop the second \"demo\"")
	}

	base, err := demoSetup()
	if err != nil {
		return Exitf(core.ExitConfigError, "set up demo environment: %s", err)
	}
	exe, err := os.Executable()
	if err != nil {
		return Exitf(core.ExitConfigError, "locate awsmux binary: %s", err)
	}

	child := exec.CommandContext(cmd.Context(), exe, args...)
	child.Stdin = os.Stdin
	child.Stdout = os.Stdout
	child.Stderr = os.Stderr
	child.Env = append(os.Environ(),
		core.AWSBinEnv+"="+exe+" fake-aws",
		"AWS_CONFIG_FILE="+filepath.Join(base, "aws-config"),
		"AWS_SHARED_CREDENTIALS_FILE="+filepath.Join(base, "aws-credentials"),
		"AWSMUX_HOME="+filepath.Join(base, "home"),
	)
	if err := child.Run(); err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			return &ExitError{Code: exitErr.ExitCode()}
		}
		return Exitf(core.ExitConfigError, "run demo command: %s", err)
	}
	return nil
}

// demoSetup writes the sandbox: a fake AWS config listing the fleet, an empty
// credentials file, and a dedicated state home.
func demoSetup() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	base := filepath.Join(home, ".awsmux", "demo")
	if err := os.MkdirAll(filepath.Join(base, "home"), 0o700); err != nil {
		return "", err
	}
	var cfg strings.Builder
	cfg.WriteString("# Generated by `awsmux demo`. This fleet is fictional.\n")
	for _, a := range demoFleet {
		fmt.Fprintf(&cfg, "[profile %s]\nregion = %s\n\n", a.Profile, a.Region)
	}
	if err := os.WriteFile(filepath.Join(base, "aws-config"), []byte(cfg.String()), 0o600); err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(base, "aws-credentials"), []byte("# empty on purpose\n"), 0o600); err != nil {
		return "", err
	}
	return base, nil
}

func printDemoTour(w interface{ Write([]byte) (int, error) }) {
	fmt.Fprint(w, `awsmux demo: a fake 12-account fleet you can break for fun.

No AWS account, credentials, or network needed. Prefix any awsmux command
with "demo" and it runs against fictional payments/search/platform/media/
data teams (prod + stage), a security-audit account, and a sandbox.

Start here:

  awsmux demo targets
      Discover the fleet; every identity is "verified" against a fake STS.

  awsmux demo run -- ec2 describe-instances --query 'Reservations[].Instances[].InstanceId'
      One command, whole fleet, merged results.

  awsmux demo run --format jsonl -- lambda list-functions
      Structured JSONL per account. One account is access-denied on
      purpose so you can see the failure taxonomy.

  awsmux demo run --profiles 'payments-*' -- ec2 describe-security-groups --filters Name=ip-permission.cidr,Values=0.0.0.0/0
      Find the security group somebody opened to the world.

  awsmux demo plan -- ec2 revoke-security-group-ingress --group-id sg-0a1b2c3d --protocol tcp --port 22 --cidr 0.0.0.0/0
      Destructive, so it will not just run: you get an immutable plan.
      Approve it (awsmux demo approve <plan-id>), then apply with the
      token. Try editing ~/.awsmux/demo/home/plans/<id>.json between
      approve and apply and watch the hash check refuse it.

  awsmux demo history
      Every run is remembered. Try "awsmux demo replay <exec-id>" too.

Agents: "awsmux demo mcp" serves the full MCP interface against the fake
fleet, so you can wire an AI agent to it with zero blast radius.

Reset anytime: rm -rf ~/.awsmux/demo
`)
}
